# Generated by Django 3.2.3 on 2021-06-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
