# Generated by Django 3.2.3 on 2021-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
        ('sale', '0004_auto_20210601_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
