# Generated by Django 3.2.3 on 2021-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20210602_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
